/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LeasingRouteImport } from './routes/leasing'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LeasingSlugRouteImport } from './routes/leasing.$slug'
import { Route as InventorySlugRouteImport } from './routes/inventory.$slug'
import { Route as EventsDescriptionRouteImport } from './routes/events.description'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'

const LeasingRoute = LeasingRouteImport.update({
  id: '/leasing',
  path: '/leasing',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LeasingSlugRoute = LeasingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LeasingRoute,
} as any)
const InventorySlugRoute = InventorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => InventoryRoute,
} as any)
const EventsDescriptionRoute = EventsDescriptionRouteImport.update({
  id: '/description',
  path: '/description',
  getParentRoute: () => EventsRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/leasing': typeof LeasingRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/events/description': typeof EventsDescriptionRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/leasing/$slug': typeof LeasingSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/leasing': typeof LeasingRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/events/description': typeof EventsDescriptionRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/leasing/$slug': typeof LeasingSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/leasing': typeof LeasingRouteWithChildren
  '/events/$slug': typeof EventsSlugRoute
  '/events/description': typeof EventsDescriptionRoute
  '/inventory/$slug': typeof InventorySlugRoute
  '/leasing/$slug': typeof LeasingSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/inventory'
    | '/leasing'
    | '/events/$slug'
    | '/events/description'
    | '/inventory/$slug'
    | '/leasing/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/inventory'
    | '/leasing'
    | '/events/$slug'
    | '/events/description'
    | '/inventory/$slug'
    | '/leasing/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/events'
    | '/inventory'
    | '/leasing'
    | '/events/$slug'
    | '/events/description'
    | '/inventory/$slug'
    | '/leasing/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  InventoryRoute: typeof InventoryRouteWithChildren
  LeasingRoute: typeof LeasingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/leasing': {
      id: '/leasing'
      path: '/leasing'
      fullPath: '/leasing'
      preLoaderRoute: typeof LeasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leasing/$slug': {
      id: '/leasing/$slug'
      path: '/$slug'
      fullPath: '/leasing/$slug'
      preLoaderRoute: typeof LeasingSlugRouteImport
      parentRoute: typeof LeasingRoute
    }
    '/inventory/$slug': {
      id: '/inventory/$slug'
      path: '/$slug'
      fullPath: '/inventory/$slug'
      preLoaderRoute: typeof InventorySlugRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/events/description': {
      id: '/events/description'
      path: '/description'
      fullPath: '/events/description'
      preLoaderRoute: typeof EventsDescriptionRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
  }
}

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
  EventsDescriptionRoute: typeof EventsDescriptionRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
  EventsDescriptionRoute: EventsDescriptionRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface InventoryRouteChildren {
  InventorySlugRoute: typeof InventorySlugRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventorySlugRoute: InventorySlugRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface LeasingRouteChildren {
  LeasingSlugRoute: typeof LeasingSlugRoute
}

const LeasingRouteChildren: LeasingRouteChildren = {
  LeasingSlugRoute: LeasingSlugRoute,
}

const LeasingRouteWithChildren =
  LeasingRoute._addFileChildren(LeasingRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  InventoryRoute: InventoryRouteWithChildren,
  LeasingRoute: LeasingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
